---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/rest-api-no-auth/groups":
    get:
      summary: Umożliwia pobieranie informacji o edycjach budżetu
      tags:
      - Groups
      description: Umożliwia pobieranie informacji o edycjach budżetu
      responses:
        '200':
          description: Lista edycji budżetu
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
                    votingStart:
                      type: string
                      format: datetime
                    votingEnd:
                      type: string
                      format: datetime
                  required:
                  - id
                  - name
                  - votingStart
                  - votingEnd
  "/rest-api-no-auth/map":
    get:
      summary: Umożliwia pobranie zwycięskich projektów złożonych dla danego obszaru
      tags:
      - Map
      description: Umożliwia pobranie zwycięskich projektów złożonych dla danego obszaru
      parameters:
      - name: southWestLongitude
        in: query
        schema:
          type: string
      - name: southWestLatitude
        in: query
        schema:
          type: string
      - name: northEastLongitude
        in: query
        schema:
          type: string
      - name: northEastLatitude
        in: query
        schema:
          type: string
      - name: status
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Lista projektow
          content:
            application/json:
              schema:
                type: array
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  lat:
                    type: string
                  lng:
                    type: string
                  progress:
                    type: integer
                required:
                - id
                - isPaper
                - title
  "/rest-api-no-auth/projects":
    get:
      summary: Umożliwia pobieranie listy projektów
      tags:
      - Projects
      description: Umożliwia pobieranie listy projektów
      parameters:
      - name: groupId
        in: query
        required: true
        schema:
          type: integer
      - name: limit
        in: query
        schema:
          type: integer
      - name: offset
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: Lista projektow
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        isPaper:
                          type: integer
                        title:
                          type: string
                        status:
                          type: integer
                        mainRegionName:
                          type: string
                        regionName:
                          type: string
                        number:
                          type: integer
                  total:
                    type: integer
                  limit:
                    type: integer
                  offset:
                    type: integer
                required:
                - id
                - isPaper
                - title
  "/rest-api-no-auth/projectDetails":
    get:
      summary: Umożliwia pobieranie szczegółowych informacji o projekcie
      tags:
      - ProjectDetails
      description: Umożliwia pobieranie szczegółowych informacji o projekcie
      parameters:
      - name: id
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Lista projektow
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  number:
                    type: integer
                  title:
                    type: string
                  status:
                    type: integer
                  description:
                    type: string
                  shortDescription:
                    type: string
                  submitted:
                    type: string
                  firstName:
                    type: string
                  lastName:
                    type: string
                  lat:
                    type: string
                  lng:
                    type: string
                  classifications:
                    type: array
                  created:
                    type: string
                  recipients:
                    type: string
                  taskLevel:
                    type: string
                  localization:
                    type: string
                  localizationExtra:
                    type: string
                  pins:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        lat:
                          type: string
                        lng:
                          type: string
                  availabilityDescription:
                    type: string
                  argumentation:
                    type: string
                  costSummary:
                    type: string
                  universalDesign:
                    type: string
                  universalDesignArgumentation:
                    type: string
                  cost:
                    type: number
                    format: float
                  mainRegionName:
                    type: string
                  history:
                    type: string
                  cocreators:
                    type: array
                    items:
                      type: object
                      properties:
                        firstName:
                          type: string
                        lastName:
                          type: string
                        name:
                          type: string
                  attachments:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                        originalName:
                          type: string
                  url:
                    type: string
                  verification:
                    type: object
                    properties:
                      resultNotes:
                        type: string
                      attachments:
                        type: array
                        items:
                          type: object
                          properties:
                            url:
                              type: string
                            originalName:
                              type: string
                  votes:
                    type: integer
                  comments:
                    type: array
                    items:
                      type: object
                      properties:
                        login:
                          type: string
                        createTime:
                          type: string
                        text:
                          type: string
                required:
                - id
                - number
                - title
  "/rest-api-no-auth/regionResults":
    get:
      summary: Pobiera wyniki głosowania dla dzielnicy
      tags:
      - RegionResults
      description: Pobiera wyniki głosowania dla dzielnicy
      parameters:
      - name: groupId
        in: query
        required: true
        schema:
          type: integer
      - name: regionId
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Pobiera wyniki głosowania dla dzielnicy
          content:
            application/json:
              schema:
                type: object
                properties:
                  regionId:
                    type: integer
                  regionName:
                    type: string
                  budget:
                    type: number
                    format: float
                  winCost:
                    type: number
                    format: float
                  cardsAccepted:
                    type: integer
                  projects:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        number:
                          type: integer
                        title:
                          type: string
                        status:
                          type: integer
                        localization:
                          type: string
                        cost:
                          type: number
                          format: float
                        costOfOperation:
                          type: number
                          format: float
                        win:
                          type: integer
                        isValidPercentage:
                          type: integer
                        validPercent:
                          type: number
                          format: float
                        cardsAccepted:
                          type: integer
                        votesAccepted:
                          type: integer
                        rejectTime:
                          type: string
                required:
                - id
                - parentId
                - name
  "/rest-api-no-auth/results":
    get:
      summary: Umożliwia pobranie listy dzielnic dla danej edycji
      tags:
      - Results
      description: Umożliwia pobieranie dzielnic dla edycji
      parameters:
      - name: groupId
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Lista dzielnic dla edycji
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    parentId:
                      type: integer
                    name:
                      type: string
                    budget:
                      type: number
                      format: float
                    votingBudget:
                      type: string
                      format: decimal
                  required:
                  - id
                  - parentId
                  - name
  "/rest-api-no-auth/status":
    get:
      summary: Pobieranie informacji o obecnie trwającej edycji
      tags:
      - Status
      responses:
        '200':
          description: Informacje o obecnie trwającej edycji
          content:
            application/json:
              schema:
                type: object
                properties:
                  description:
                    type: string
                  status:
                    type: string
                  projectsInExecution:
                    type: string
                required:
                - id
                - title
                - content
servers:
- url: https://bo.testum.warszawa.pl
